// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type FriendRequest struct {
	Senderid   int `json:"senderid"`
	Receiverid int `json:"receiverid"`
}

type Game struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Price         int       `json:"price"`
	Banner        int       `json:"banner"`
	CreatedAt     time.Time `json:"createdAt"`
	MatureContent bool      `json:"matureContent"`
}

type GameDetail struct {
	ID                 int64  `json:"id"`
	Hoursplayed        int    `json:"hoursplayed"`
	Description        string `json:"description"`
	Developer          string `json:"developer"`
	Publisher          string `json:"publisher"`
	Systemrequirements string `json:"systemrequirements"`
}

type GameItem struct {
	Gameid   int    `json:"gameid"`
	Itemid   int64  `json:"itemid"`
	Itemname string `json:"itemname"`
}

type GamePromo struct {
	Gameid   int64     `json:"gameid"`
	Discount int       `json:"discount"`
	ValidTo  time.Time `json:"validTo"`
}

type GameReview struct {
	Gameid   int    `json:"gameid"`
	Review   string `json:"review"`
	Userid   int    `json:"userid"`
	Upvote   int    `json:"upvote"`
	Downvote int    `json:"downvote"`
	Date     string `json:"date"`
}

type GameSales struct {
	Gameid      int    `json:"gameid"`
	Countryname string `json:"countryname"`
	Salescount  int    `json:"salescount"`
}

type GameSlideshow struct {
	Gameid      int    `json:"gameid"`
	Link        int    `json:"link"`
	ContentType string `json:"contentType"`
}

type GameTag struct {
	Gameid  int64  `json:"gameid"`
	Tagname string `json:"tagname"`
}

type ReportUser struct {
	Reporteduserid  int       `json:"reporteduserid"`
	Userwhoreportid int       `json:"userwhoreportid"`
	CreatedAt       time.Time `json:"createdAt"`
}

type User struct {
	ID          int64  `json:"id"`
	Fullname    string `json:"fullname"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Country     string `json:"country"`
	IsSuspended bool   `json:"isSuspended"`
	Balance     int    `json:"balance"`
}

type UserBadge struct {
	Userid int `json:"userid"`
	Badge  int `json:"badge"`
}

type UserFriends struct {
	Userid   int `json:"userid"`
	Friendid int `json:"friendid"`
}

type UserGame struct {
	Userid int `json:"userid"`
	Gameid int `json:"gameid"`
}

type UserInventory struct {
	Userid   int `json:"userid"`
	Gameid   int `json:"gameid"`
	Itemid   int `json:"itemid"`
	Quantity int `json:"quantity"`
}

type UserNotif struct {
	Userid      int    `json:"userid"`
	Newsid      int    `json:"newsid"`
	ContentType string `json:"contentType"`
}

type UserProfile struct {
	Userid  int    `json:"userid"`
	Image   int    `json:"image"`
	Level   int    `json:"level"`
	Summary string `json:"summary"`
	Status  string `json:"status"`
}

type UserWishlist struct {
	Userid int `json:"userid"`
	Gameid int `json:"gameid"`
}
