// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AnimatedAvatar struct {
	Userid   int    `json:"userid"`
	Avatarid int    `json:"avatarid"`
	Avatar   string `json:"avatar"`
	Price    int    `json:"Price"`
	Active   bool   `json:"active"`
}

type Cart struct {
	Gameid int `json:"gameid"`
}

type Country struct {
	Countryname string  `json:"countryname"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

type FriendRequest struct {
	Senderid   int `json:"senderid"`
	Receiverid int `json:"receiverid"`
}

type Game struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Price         int       `json:"price"`
	Banner        int       `json:"banner"`
	CreatedAt     time.Time `json:"createdAt"`
	MatureContent bool      `json:"matureContent"`
}

type GameBadge struct {
	Badgeid int    `json:"badgeid"`
	Gameid  int    `json:"gameid"`
	Badge   string `json:"badge"`
}

type GameDetail struct {
	ID                 int64  `json:"id"`
	Hoursplayed        int    `json:"hoursplayed"`
	Description        string `json:"description"`
	Developer          string `json:"developer"`
	Publisher          string `json:"publisher"`
	Systemrequirements string `json:"systemrequirements"`
}

type GameItem struct {
	Gameid  int    `json:"gameid"`
	Itemid  int    `json:"itemid"`
	Itemn   string `json:"itemn"`
	Summary string `json:"summary"`
	Name    string `json:"name"`
}

type GamePromo struct {
	Gameid   int64     `json:"gameid"`
	Discount int       `json:"discount"`
	ValidTo  time.Time `json:"validTo"`
}

type GameReview struct {
	Gameid      int       `json:"gameid"`
	Review      string    `json:"review"`
	Userid      int       `json:"userid"`
	Upvote      int       `json:"upvote"`
	Downvote    int       `json:"downvote"`
	Date        time.Time `json:"date"`
	Link        int       `json:"link"`
	ContentType string    `json:"ContentType"`
	Positive    bool      `json:"positive"`
	Helpful     int       `json:"helpful"`
}

type GameSales struct {
	Gameid      int    `json:"gameid"`
	Countryname string `json:"countryname"`
	Salescount  int    `json:"salescount"`
}

type GameSlideshow struct {
	Gameid      int    `json:"gameid"`
	Link        int    `json:"link"`
	ContentType string `json:"contentType"`
}

type GameTag struct {
	Gameid  int64  `json:"gameid"`
	Tagname string `json:"tagname"`
}

type Market struct {
	Sellerid int    `json:"sellerid"`
	Itemid   int    `json:"itemid"`
	Gameid   int    `json:"gameid"`
	Price    int    `json:"price"`
	Type     string `json:"type"`
	Buyerid  int    `json:"buyerid"`
}

type ReportUser struct {
	Reporteduserid  int       `json:"reporteduserid"`
	Userwhoreportid int       `json:"userwhoreportid"`
	CreatedAt       time.Time `json:"createdAt"`
}

type Transaction struct {
	Sellerid  int       `json:"sellerid"`
	Buyerid   int       `json:"buyerid"`
	Price     int       `json:"price"`
	Itemid    int       `json:"itemid"`
	CreatedAt time.Time `json:"createdAt"`
}

type UnsuspensionRequest struct {
	Userid int    `json:"userid"`
	Status string `json:"status"`
}

type User struct {
	ID          int64  `json:"id"`
	Fullname    string `json:"fullname"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	Country     string `json:"country"`
	IsSuspended bool   `json:"isSuspended"`
	Balance     int    `json:"balance"`
	Point       int    `json:"point"`
}

type UserActivities struct {
	Userid    int       `json:"userid"`
	Activity  string    `json:"activity"`
	CreatedAt time.Time `json:"createdAt"`
}

type UserAvatar struct {
	Userid   int  `json:"userid"`
	Avatarid int  `json:"avatarid"`
	Price    int  `json:"price"`
	Active   bool `json:"active"`
}

type UserBackground struct {
	Userid       int  `json:"userid"`
	Backgroundid int  `json:"backgroundid"`
	Price        int  `json:"price"`
	Active       bool `json:"active"`
}

type UserBadge struct {
	Userid int `json:"userid"`
	Gameid int `json:"gameid"`
	Badge  int `json:"badge"`
}

type UserChatSticker struct {
	Userid      int    `json:"userid"`
	Stickerid   int    `json:"stickerid"`
	Chatsticker string `json:"chatsticker"`
	Price       int    `json:"Price"`
	Active      bool   `json:"active"`
}

type UserCode struct {
	Userid int `json:"userid"`
	Code   int `json:"code"`
}

type UserComment struct {
	Gameid      int    `json:"gameid"`
	Posterid    int    `json:"posterid"`
	Commenterid int    `json:"commenterid"`
	Review      string `json:"review"`
	Comment     string `json:"comment"`
}

type UserFriends struct {
	Userid   int `json:"userid"`
	Friendid int `json:"friendid"`
}

type UserGame struct {
	Userid int `json:"userid"`
	Gameid int `json:"gameid"`
}

type UserGameItem struct {
	Userid int `json:"userid"`
	Gameid int `json:"gameid"`
	Itemid int `json:"itemid"`
}

type UserInventory struct {
	Userid   int `json:"userid"`
	Gameid   int `json:"gameid"`
	Itemid   int `json:"itemid"`
	Quantity int `json:"quantity"`
}

type UserMiniBackground struct {
	Userid       int  `json:"userid"`
	Backgroundid int  `json:"backgroundid"`
	Price        int  `json:"price"`
	Active       bool `json:"active"`
}

type UserNotif struct {
	Userid      int    `json:"userid"`
	Friendid    int    `json:"friendid"`
	News        string `json:"news"`
	ContentType string `json:"contentType"`
}

type UserProfile struct {
	Userid  int    `json:"userid"`
	Image   int    `json:"image"`
	Level   int    `json:"level"`
	Summary string `json:"summary"`
	Status  string `json:"status"`
}

type UserProfileComment struct {
	Userid      int       `json:"userid"`
	Commenterid int       `json:"commenterid"`
	Comment     string    `json:"comment"`
	CreatedAt   time.Time `json:"createdAt"`
}

type UserTheme struct {
	Userid int    `json:"userid"`
	Hex    string `json:"hex"`
}

type UserURL struct {
	Userid int    `json:"userid"`
	URL    string `json:"url"`
}

type UserWishlist struct {
	Userid int `json:"userid"`
	Gameid int `json:"gameid"`
}

type WalletCode struct {
	Code   int `json:"code"`
	Amount int `json:"amount"`
}
